### ISSUE TITLE
Demo Broken?

### ISSUE THREAD

**Issue by rawrmonstar** [matthewp/haunted-starter-app#1]
https://codesandbox.io/s/github/matthewp/haunted-starter-app doesn't seem to work anymore. This library looks super cool, I would love to be able to play around with it.

**edit:** It must be something with codesandbox because cloning the repo locally and via glitch works fine. Maybe consider adding a link to remix with glitch unless it can start working in codesandbox...

[![Remix on Glitch](https://cdn.glitch.com/2703baf2-b643-4da7-ab91-7ee2a2d00b5b%2Fremix-button.svg)](https://glitch.com/edit/#!/remix/matthewp/haunted-starter-app)

**Comment by matthewp** [comment]
It seems like something changed with codesandbox where it always transpiled to ES5. I'm looking at it.
