### ISSUE TITLE
index.html is missing a bunch of stuff

### ISSUE THREAD

**Issue by andria-dev** [matthewp/haunted-starter-app#6]
List of things missing from `index.html` file:

- Closing tag for `<html>`
- `<head>` tags
- `<body>` tags
- Responsive `<meta>` tag

The file also needs to be formatted as it has no indentation whatsoever right now.

**Comment by matthewp** [comment]
head and body tags are optional so I always omit them unless there is a reason to include them. Closing tag for html is optional so I omit it.  `<meta>` tag would be nice though.

**Comment by andria-dev** [comment]
I think it'd be fine to omit it when prototyping, however, this is a starter app so it would seem logical to include all the bells and whistles here. I think it's just easier for others to read.

**Comment by andria-dev** [comment]
Also the title still says "Parcel Sandbox" so that should probably be changed to "Haunted App"
